#config_version=5

mode:
    # start_events: s_plunger_lane_active
    # start_events: ball_starting
    start_events: plunger_lane_released{current_player.skill_shot_taken == 0}
    stop_events:
        - skill_success
        - skill_failed
        - ball_drain
    priority: 500

shots:
    skill_1:
        switch: s_target_jukebox
        profile: skill_shot_profile
        advance_events: mode_skill_shot_started
        show_tokens:
            light: l_jukebox_rgb
    # skill_2:
    #     switch: s_pop_bumper
    #     profile: skill_shot_profile
    #     advance_events: mode_skill_shot_started
    #     show_tokens:
    #         light: l_pop_bumper_rgb
    # skill_3:
    #     switch: s_lane_r
    #     profile: skill_shot_profile
    #     # show_tokens:
    #     #     light: l_lane_r

shot_groups:
    skill_shot:
        shots: skill_1 #, skill_2 #, skill_3
        # rotate_left_events: s_left_flipper_active
        # rotate_right_events: s_right_flipper_active
        reset_events:
        - skill_success
        - skill_failed
        - ball_drain

shot_profiles:
    skill_shot_profile:
        states:
         - name: unlit
           show: off
         - name: flashing
           show: flash_color
           show_tokens:
             color: red
           speed: 4
         - name: lit
           show: on
        loop: yes

variable_player:
  skill_success:
    score: 37
  timer_skill_shot_timeout_tick:
    skill_shot_timeout_variable:
      int: device.timers.skill_shot_timeout.ticks
      action: set
  skill_shot_taken_true:
    skill_shot_taken:
      int: 1
      action: set
  # player_turn_started:
  #   skill_shot_taken:
  #     int: 0
  #     action: set

sound_player:
  skill_success:
    voice_skill:
      action: play
      loops: 0
  skill_failed:
    sfx_skill_fail:
      action: play
      loops: 0

slides:
  _overwrite: true
  skill_success_slide:
    widgets:
      - type: video
        video: skill
        end_behavior: stop
    expire: 2s
    # transition:
    #   type: wipe
    #   duration: 2s
    #   direction: right
    # transition_out:
    #   type: fade_away
  show_timer_skill_shot:
    widgets:
    - type: Text
      text: (player|skill_shot_timeout_variable)

# slide_player:
#   skill_success:  skill_success_slide

timers:
  skill_shot_timeout:
    start_value: 5
    end_value: -1 #INFO: timeout of skill_shot
    direction: down
    tick_interval: 1s
    start_running: false
    control_events:
    - action: restart
      event: balldevice_bd_plunger_ball_eject_success #INFO: plunger device
      
state_machines:
   skill_shot_success:
        # debug: True
        states:
            start:
                label: skill_shot ready
            success:
                label: skill_shot success
                events_when_started: skill_success, skill_shot_taken_true
            failed:
                label: skill_shot fail
                events_when_started: skill_failed, skill_shot_taken_true
        transitions:
            - source: start
              target: success
              events: skill_shot_flashing_hit
            - source: start
              target: failed
              events: skill_shot_unlit_hit, timer_skill_shot_timeout_complete
