#config_version=5

slides:
    attract_started:
        widgets:
              - type: video
                video: attract_deadwood
                end_behavior: loop

slide_player:
  mode_attract_started: attract_started

sound_player:
  mode_attract_started:
      song_attract:
          action: play
          loops: -1
  mode_attract_stopped:
      song_attract:
          action: stop