#config_version=5

# - duration: 10s
# slides:
#   attract_started:
#     widgets:
#       - type: video
#         video: attract_deadwood #video is 10s 
#         end_behavior: loop

show_player:
  mode_attract_started: attract_display_loop
  # shift_left_event: s_left_flipper_active
  # shift_right_event: s_right_flipper_active

sound_player:
  mode_attract_started:
      song_attract:
          action: play
          loops: -1
  mode_attract_stopped:
      song_attract:
          action: stop