#config_version=5

mode:
  start_events: ball_starting
  priority: 100

sound_player:
    mode_base_started:
        song_01:
            action: play
            loops: -1
    mode_base_stopped:
        song_01:
            action: stop
    s_target_jukebox_active:
      sfx_coin:
          action: play
          loops: 0
    s_left_slingshot_active:
      sfx_punch_1:
        action: play
        loops: 0
    s_right_slingshot_active:
      sfx_punch_2:
        action: play
        loops: 0

variable_player:
#INFO: variables to reset for players after specific events
  ball_drain:
    skill_shot_taken:
      int: 0
      action: set

#INFO: regular scoring stuff
  s_left_slingshot_active:
    score: 20
  s_right_slingshot_active:
    score: 20

  # s_left_flipper_active:
  #   score: -5
  # s_right_flipper_active:
  #   score: -5

# TODO: mode_skill_shot_(ended or failed), need to change the scoring
  s_spinner_active:
    # spinner_rotations: 1
    score: 5
  s_target_jukebox_active:
    score: 5

  s_drop_target_left_active:
    score: 25
  s_drop_target_middle_active:
    score: 25
  s_drop_target_right_active:
    score: 25
  
  # s_varitarget_0_active:
    # score: 5
  s_varitarget_1_active:
    score: 10
  s_varitarget_2_active:
    score: 15
  s_varitarget_3_active:
    score: 20
  s_varitarget_4_active:
    score: 25
  s_varitarget_5_active:
    score: 30
  s_varitarget_6_active:
    score: 35
  s_varitarget_7_active:
    score: 40

  s_pop_bumper_active:
    score: 25
    # l_pop_bumper_rgb_on


# event_player:
#   flipper_cardle_active:
#       score: -12

# timed_switches:
#   flipper_cradle:
#     switch_tags: left_flipper, right_flipper
#     time: 3s
#     events_when_active: flipper_cradle
#     events_when_released: flipper_cradle_release

slide_player:
  skill_success: skill_success_slide
    
# sound_player:
#   ball_ending:
#     sfx_ball_drain:
#       action: play
#       loops: 0