#config_version=5

mode:
  start_events: ball_starting
  priority: 100

variable_player:
  s_left_slingshot_active:
    score: 20
  s_right_slingshot_active:
    score: 20

  s_left_flipper_active:
    score: -5
  s_right_flipper_active:
    score: -5

# TODO: mode_skillshot_(ended or failed), need to change the scoring
  s_spinner_active:
    spinner_rotations: 1
    score: 5
  s_target_jukebox_active:
    score: 5

slide_player:
  mode_base_started:
      widgets:
        - type: text
          text: (score)
          number_grouping: true
          min_digits: 2
          font_size: 100
        - type: text
          text: Drinker (number)
          y: 10
          x: 10
          font_size: 50
          anchor_x: left
          anchor_y: bottom
        - type: text
          text: Ball (ball)
          y: 10
          x: right-10
          anchor_x: right
          anchor_y: bottom
          font_size: 50
  skill_success:  skill_success_slide