#config_version=5

mode:
  start_events: ball_starting
  priority: 100

variable_player:
  s_left_slingshot_active:
    score: 20
  s_right_slingshot_active:
    score: 20

  s_left_flipper_active:
    score: -5
  s_right_flipper_active:
    score: -5

# TODO: mode_skillshot_(ended or failed), need to change the scoring
  s_spinner_active:
    spinner_rotations: 1
    score: 5
  s_target_jukebox_active:
    score: 5

  s_drop_target_left_active:
    score: 25
  s_drop_target_middle_active:
    score: 25
  s_drop_target_right_active:
    score: 25
  


slide_player:
  skill_success: skill_success_slide
  
sound_player:
  ball_drain:
    sfx_ball_drain:
      action: play
      loops: 0
