#config_version=5

mode:
  start_events: ball_starting
  priority: 500

event_player:
  mode_smart_drop_target_started: drop_smart_drop
  s_varitarget_6_active: lift_smart_drop

coil_player:
  lift_smart_drop:
    c_smart_drop_target_reset:
      pulse_ms: 40
  drop_smart_drop:
    c_smart_drop_target_knockdown:
      pulse_ms: 40