#config_version=5

mode_settings:
  display_delay_ms: 1s
  hurry_up_delay_ms: 0
  bonus_entries:
    - event: bonus_complete_spins
      score: current_player.completed_spins * 200
    #   player_score_entry: (device.counters.spins_counter.value)
    # - event: bonus_dropbanks
    #   score: player.counters.dropbank_completions.value * 20
      skip_if_zero: false
      player_score_entry: spins
      reset_player_score_entry: True

slides:
  bonus_start_slide:
    widgets:
      - type: text
        text: Bonus
        font_size: 60
        bold: true
        anchor_x: center
        anchor_y: center
        # x: center
        # y: top-100
  bonus_complete_spins_slide:
    widgets:
      - type: Text
        text: COMPLETED SPINS
        number_grouping: true
        min_digits: 1
        font_size: 60
        bold: true
        anchor_x: center
        anchor_y: center
      - type: text
        text: (player|completed_spins)
        number_grouping: true
        min_digits: 1
        font_size: 60
        bold: true
        anchor_x: center
        anchor_y: center
        y: center-100
        # x: center
        # y: top-100
  # bonus_game_room_dropbanks_slide:
  #   widgets:
  #     - type: Text
  #       text: COMPLETED GAME ROOMS (player|dropbanks)
  #       font_size: 60
  #       bold: true
  #       anchor_x: center
  #       anchor_y: center
  #       x: center
  #       y: top-100
  # bonus_multiplier_slide:
  #   - type: text
  #     text: "Multiplier"
  #     bold: true
  #     anchor_x: center
  #     anchor_y: center
  #     y: top+100
  #   - type: text
  #     text: "(multiplier)X"
  #     number_grouping: true
  #     min_digits: 1
  #     font_size: 60
  #     bold: true
  #     anchor_x: center
  #     anchor_y: center
  #     y: top+100
  bonus_total_slide:
    - type: text
      text: "Total Bonus"
      font_size: 60
      bold: true
      anchor_x: center
      anchor_y: center
    - type: text
      text: (score)
      number_grouping: true
      min_digits: 2
      font_size: 60
      bold: true
      anchor_x: center
      anchor_y: center
      y: center-100

slide_player:
  mode_bonus_started: bonus_start_slide
  bonus_complete_spins{player.counters.spins_counter.value>0}: bonus_complete_spins_slide
  # bonus_game_room_dropbanks: bonus_game_room_dropbanks_slide
  bonus_total: bonus_total_slide