#config_version=5

mode:
  start_events: ball_starting
  priority: 500

counters:
  spins_counter:
    count_events: s_spinner_active
    reset_on_complete: True
    disable_on_complete: False
    starting_count: 0
    count_complete_value: 10
    direction: up
    events_when_complete: increment_completed_spins
    persist_state: False

variable_player:
  increment_completed_spins:
    completed_spins: 1