#config_version=5

assets:
  sounds:
    default:
      load: on_demand
    music:
      load: preload
      track: music
    sfx:
      load: preload
      track: sfx
    voice:
      load: preload
      track: voice