#config_version=5

hardware:
    # platform: p3_roc #INFO: comment for virtual
    # driverboards: pdb #INFO: comment for virtual
    platform: smart_virtual #uncomment for virtual

config:
- hardware.yaml
- hardware_virtual.yaml #uncomment for virtual
- shots.yaml
- keyboard.yaml

modes:
- base
- tilt

#INFO: bootup and start modes
slides:
    welcome_slide:
        widgets:
              - type: image
                image: ZukiDogLogo
    attract_started:
        widgets:
              - type: video
                video: attract_deadwood
                end_behavior: loop
slide_player:
    init_done: welcome_slide
    mode_attract_started: attract_started

