#config_version=5

hardware:
    platform: p3_roc #INFO: comment for virtual
    driverboards: pdb #INFO: comment for virtual
    # platform: smart_virtual #INFO: UNcomment for virtual

config:
- hardware.yaml
# - hardware_virtual.yaml #INFO: UNcomment for virtual
- assets.yaml
- sounds.yaml
- styles.yaml
- shots.yaml
- timers.yaml
- variables
- keyboard.yaml

modes:
- attract
- base
- high_score
- tilt
# - skill_shot_select
- skill_shot
- drop_targets
- varitarget
- spinner
- pop_bumper
- laser_kick
- smart_drop_target
- bonus
- multiball
- fork_lock

#INFO: bootup mode
slides:
    welcome_slide:
        widgets:
              - type: image
                image: ZukiDogLogo
slide_player:
    init_done: welcome_slide
#     mode_attract_started:
#         welcome_slide:
#             action: remove