#config_version=5

hardware:
    platform: p3_roc
    driverboards: pdb
#    platform: smart_virtual



modes:
    - base
    - tilt




switches:
    s_left_flipper:
        number: A0-B1-0
        tags: left_flipper
    s_right_flipper:
        number: A0-B1-2
        tags: right_flipper

    s_trough1:
        number: A0-B0-1
    s_trough2:
        number: A0-B0-4
    s_trough3:
        number: A0-B0-3
    s_trough4:
        number: A0-B0-2
    s_trough_jam:
        number: A0-B0-0


#s_plunger_lane is where the ball rests in the lane
    s_plunger_lane:
        number: A0-B0-5
#s_launch_button only needed for virtual game because no manual plunger
#    s_launch_button:
#        number: A1-B0-7

    s_start:
        number: A0-B1-1
        tags: start

#s_right_inlane is only there to show playfield active, once more switches are on the playfield this will not be necessary
#    s_right_inlane:
#        number: A1-B1-2
#        tags: playfield_active

    s_left_slingshot:
        number: A0-B0-6
#        tags: playfield_active
    s_right_slingshot:
        number: A0-B0-7
#        tags: playfield_active

    s_tilt:
        number: A0-B1-3
        tags: tilt_warning

        
coils:    
    c_flipper_left_main:
        number: A0-B1-2
        default_pulse_ms: 30
    c_flipper_left_hold:
        number: A0-B1-3
        allow_enable: true
    c_flipper_right_main:
        number: A0-B0-1
        default_pulse_ms: 30
    c_flipper_right_hold:
        number: A0-B0-2
        allow_enable: true

    c_trough_eject:
        number: A0-B0-3
        default_pulse_ms: 20

    c_plunger:
        number: A0-B0-0
        default_pulse_ms: 20

    c_left_slingshot:
        number: A0-B1-1
        default_pulse_ms: 10
    c_right_slingshot:
        number: A0-B1-0
        default_pulse_ms: 10

#only needed for virtual
#    c_launch_button:
#        number: A1-B0-6
#        default_pulse_ms: 20


autofire_coils:
    left_slingshot:
        coil: c_left_slingshot
        switch: s_left_slingshot
    right_slingshot:
        coil: c_right_slingshot
        switch: s_right_slingshot

ball_devices:
    bd_trough:
        ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough_jam
        eject_coil: c_trough_eject
        tags: trough, home, drain
        jam_switch: s_trough_jam
        eject_coil_jam_pulse: 5ms
        eject_targets: bd_plunger
        debug: yes


    bd_plunger:
        ball_switches: s_plunger_lane
        eject_coil: c_plunger
        mechanical_eject: true
        eject_timeouts: 1s





playfields:
    playfield:
        tags: default
        default_source_device: bd_plunger





#virtual_platform_start_active_switches:
#    - s_trough1
#    - s_trough2
#    - s_trough3





flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
       # enable_events: machine_reset_phase_3
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
       # enable_events: machine_reset_phase_3





displays:
    window:
        width: 800
        height: 600
slides:
    welcome_slide:
        widgets:
              - type: text
                text: PINBALL!
    attract_started:
        widgets:
              - type: video
                video: attract_deadwood_alt
                end_behavior: loop
slide_player:
    init_done: welcome_slide
    mode_attract_started: attract_started





keyboard:
    z:
        switch: s_left_flipper
    "/":
        switch: s_right_flipper
    s:
        switch: s_start
    q:
        switch: s_right_inlane
    p:
        switch: s_plunger_lane
    1:
        switch: s_trough1
    2:
        switch: s_trough2
    3:
        switch: s_trough3
    4:
        switch: s_trough4
    9:
        switch: s_left_slingshot
    l:
        switch: s_launch_button
    t:
        switch: s_tilt