#config_version=5

virtual_platform_start_active_switches: s_trough1, s_trough2, s_trough3

window:
  fullscreen: false

keyboard:
    debug: true

switches:
    c_launch_button: 
        number: A1-B0-6 
        # default_pulse_ms: 20
    s_launch_button:
        number: A1-B0-7

#INFO: only there to show playfield active, once more switches are on the playfield this will not be necessary
    s_right_inlane:
        number: A1-B1-2
        tags: playfield_active

    s_left_slingshot:
        # tags: playfield_active
    s_right_slingshot:
        # tags: playfield_active

flippers:
    left_flipper:
        enable_events: machine_reset_phase_3
    right_flipper:
        enable_events: machine_reset_phase_3


