#config_version=5

# mpf:
#     default_pulse_ms: 20

game:
    balls_per_game: 3
    max_players: 4

machine:
  balls_installed: 4

window:
  width: 1366
  height: 768
  title: Deadwood
  resizable: false
  fullscreen: true
  borderless: true
  exit_on_escape: true
  source_display: window
  
displays:
    window:
        width: 1366
        height: 768

switches:
    s_left_flipper:
        number: A0-B1-0
        tags: left_flipper
    s_right_flipper:
        number: A0-B1-2
        tags: right_flipper

    s_trough1:
        number: A0-B0-1
    s_trough2:
        number: A0-B0-4
    s_trough3:
        number: A0-B0-3
    s_trough4:
        number: A0-B0-2
    s_trough_jam:
        number: A0-B0-0

#INFO: switch to detect the ball resting in the lane
    s_plunger_lane:
        number: A0-B0-5

    s_start:
        number: A0-B1-1
        tags: start

#INFO: only there to show playfield active, once more switches are on the playfield this will not be necessary
#INFO:START only needed for virtual
    # s_right_inlane:
    #     number: A1-B1-2
    #     tags: playfield_active
#INFO:STOP only needed for virtual

    s_left_slingshot:
        number: A0-B0-6
    s_right_slingshot:
        number: A0-B0-7

    s_spinner:
        number: A0-B1-7
    s_target_jukebox:
        number: A0-B1-6

    s_tilt:
        number: A0-B1-3
        tags: tilt_warning

coils:    
    c_flipper_left_main:
        number: A0-B1-2
        default_pulse_ms: 30
    c_flipper_left_hold:
        number: A0-B1-3
        allow_enable: true
    c_flipper_right_main:
        number: A0-B0-1
        default_pulse_ms: 30
    c_flipper_right_hold:
        number: A0-B0-2
        allow_enable: true

    c_trough_eject:
        number: A0-B0-3
        default_pulse_ms: 20

    c_plunger:
        number: A0-B0-0
        default_pulse_ms: 20

    c_left_slingshot:
        number: A0-B1-1
        default_pulse_ms: 10
    c_right_slingshot:
        number: A0-B1-0
        default_pulse_ms: 10

autofire_coils:
    left_slingshot:
        coil: c_left_slingshot
        switch: s_left_slingshot
    right_slingshot:
        coil: c_right_slingshot
        switch: s_right_slingshot

ball_devices:
    bd_trough:
        ball_switches: s_trough1, s_trough2, s_trough3, s_trough4
        eject_coil: c_trough_eject
        tags: trough, home, drain
        jam_switch: s_trough_jam
        eject_coil_jam_pulse: 5ms
        entrance_count_delay: 300ms
        eject_timeouts: 1s
        eject_targets: bd_plunger
        # debug: yes

    bd_plunger:
        ball_switches: s_plunger_lane
        eject_coil: c_plunger
        mechanical_eject: true
        entrance_count_delay: 300ms
        eject_timeouts: 1s

playfields:
    playfield:
        tags: default
        default_source_device: bd_plunger

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper


