#config_version=5

virtual_platform_start_active_switches: s_trough1, s_trough2, s_trough3

window:
  fullscreen: false

keyboard:
    debug: true

switches:
    c_launch_button: 
        number: A1-B0-6 
        # default_pulse_ms: 20
    s_launch_button:
        number: A1-B0-7

#INFO: only there to show playfield active, once more switches are on the playfield this will not be necessary
    s_right_inlane:
        number: A1-B1-2
        tags: playfield_active

#     s_left_slingshot:
#         number: A0-B0-6
#         # tags: playfield_active #INFO: uncomment for virtual
#     s_right_slingshot:
#         number: A0-B0-7
#         # tags: playfield_active #INFO: uncomment for virtual

# flippers:
#     left_flipper:
#         main_coil: c_flipper_left_main
#         hold_coil: c_flipper_left_hold
#         activation_switch: s_left_flipper
#         enable_events: machine_reset_phase_3 #INFO: uncomment for virtual
#     right_flipper:
#         main_coil: c_flipper_right_main
#         hold_coil: c_flipper_right_hold
#         activation_switch: s_right_flipper
#         enable_events: machine_reset_phase_3 #INFO: uncomment for virtual


