keyboard:
    z:
        switch: s_left_flipper
    "/":
        switch: s_right_flipper
    s:
        switch: s_start
    q:
        switch: s_right_inlane
    p:
        switch: s_plunger_lane
    1:
        switch: s_trough1
    2:
        switch: s_trough2
    3:
        switch: s_trough3
    4:
        switch: s_trough4
    9:
        switch: s_left_slingshot
    l:
        switch: s_launch_button
    t:
        switch: s_tilt