#config_version=5

keyboard:
    z:
        switch: s_left_flipper
    "/":
        switch: s_right_flipper
    s:
        switch: s_start

    q:
        switch: s_right_inlane
    p:
        switch: s_plunger_lane

    1:
        switch: s_trough1
    2:
        switch: s_trough2
    3:
        switch: s_trough3
    4:
        switch: s_trough4
    5:
        switch: s_trough_jam

    7:
        switch: s_target_jukebox
    8:
        switch: s_spinner

    9:
        switch: s_left_slingshot
    0:
        switch: s_right_slingshot

    x:
        switch: s_drop_target_left
    c:
        switch: s_drop_target_middle
    v:
        switch: s_drop_target_right #INFO: game room entrance

    w:
        switch: s_varitarget_0
    e:
        switch: s_varitarget_1
    r:
        switch: s_varitarget_2
    t:
        switch: s_varitarget_3
    y:
        switch: s_varitarget_4
    u:
        switch: s_varitarget_5
    i:
        switch: s_varitarget_6
    o:
        switch: s_varitarget_7

    d:
        switch: s_pop_bumper

    f:
        switch: s_laser_kick_prox
    g:
        switch: s_smart_drop_target

    l:
        switch: s_launch_button
    b:
        switch: s_tilt