#config_version=5

player_vars:
  #INFO: mode --> spinning
  completed_spins:
    value_type: int
    initial_value: 0
  skill_shot_taken:
    value_type: int
    initial_value: 0
  pops_total:
    value_type: int
    initial_value: 0
