#config_version=5

slides:
  _overwrite: true
  tilt_warning_1:
    widgets:
      - type: video
        video: Warning-1
        end_behavior: stop
    expire: 2s
  tilt_warning_2:
    widgets:
      - type: video
        video: Warning-2
        end_behavior: stop
    expire: 1500ms
  tilt:
    widgets:
      - type: video
        video: Tilt
        end_behavior: stop
    expire: 7s

tilt:
  #INFO: the following are the defaults only copy those if you want to change them
  multiple_hit_window: 2s
  settle_time: 7s
  warnings_to_tilt: 3