#config_version=5
mode:
  start_events:
      - ball_starting
      - stop_fork_lock
  stop_events: start_fork_lock

event_player:
  # mode_fork_target_started: drop_fork
  s_fork_up_down_active:
      - lift_fork
      - start_fork_lock
      # then stop event, add code to handle up_down switch target when multiball active. example: 3 hits releases ball... 

coil_player:
  lift_fork:
    c_fork_up:
      pulse_ms: 140
  drop_fork:
    c_fork_eject:
      pulse_ms: 40